Review
korvintaG/blog-customizer pull request #1
Opened 2024-05-01 09:43 UTC by korvintaG

На первую проверку

2024-05-01 11:20 UTC, olgalatkina requested changes
Добрый день!

**У вас получилась отличная работа:**
- Полностью реализован весь функционал.
- Для условного добавления css-классов спользуется библиотека `clsx`.
- Обработчик сохранения данных вызывается при отправке формы.
- Для закрытия сайдбара по клику вне сайдбара используется кастомный хук.
- Код хорошо типизирован.
- Прекрасные комментарии.

**Но есть один момент, который надо поправить:**
- [ ] По макету расстояние между элементами формы 50px: https://yadi.sk/d/_vy8y0NXA0t3PQ
 
**Правки можно лучше остаются на ваше усмотрение:**
- [ ] Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx` (см. компоненты `Article` и `App`).
- [ ] Вы довольно много изменили в css. Надеюсь, вам понравится интересная задача: убрать горизонтальную прокрутку у сайдбара и дыру в фоне: https://disk.yandex.ru/d/NLJNChQ-Ns5rcg
 
Успешного рефакторинга!

2024-05-01 11:20 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, { [styles.container_open]: isOpen })}>
**Отлично:**
Здорово, что для условного добавления css-классов вы используете библиотеку `clsx`.

2024-05-01 11:20 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 41px;
**Надо исправить:**
Стоит поправить расстояние между элементами формы, по макету оно 50px: https://yadi.sk/d/_vy8y0NXA0t3PQ

2024-05-01 11:20 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const toggleOpen = (): void => setOpen(!isOpen);
**Можно лучше:** 
Нет необходимости создавать дополнительные функции обработчики если они сами по себе ничего не делают, можно использовать просто функции сеттеры возвращаемые `useState`.

В React ссылка на функцию-сеттер, возвращаемую хуком `useState`, обычно является стабильной. Это означает, что она будет оставаться той же самой функцией при каждом рендере компонента.

Так в этом компоненте вы приняли в пропе `onSet` функцию сеттер `setArticleState` и использовали её внутри компонента.

2024-05-01 11:20 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					onSubmit={handleSubmit}
**Отлично:**
Здорово, что обработчик сохранения данных вызывается при отправке формы.

2024-05-01 11:20 UTC, olgalatkina commented on src/components/select/hooks/useOutsideClickClose.ts
> + */
**Отлично:**
Корректное обращение с кодом библиотечного компонента и прекрасные комментарии. Браво!

2024-05-01 11:20 UTC, olgalatkina commented on src/index.tsx
>  			className={clsx(styles.main)}
**Можно лучше:**
Для одиночных селекторов не стоит использовать библиотеку `clsx`.

2024-05-01 11:20 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
**Можно лучше:**
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-05-01 11:20 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useOutsideClickClose({
Можете попробовать другое готовое решение, в нём так же реализовано закрытие по `Escape`:
```
import { useEffect } from "react";

type TUseClose = {
  isOpen: boolean;
  onClose: () => void;
  rootRef: React.RefObject<HTMLElement>;
};

// Кастомные хуки всегда должны начинаться с глагола `use`, чтобы реакт понял, что это хук. 
// Он следит за их вызовами
export function useClose({isOpen, onClose, rootRef}: TUseClose) {
  useEffect(() => {
    if (!isOpen) return; // останавливаем действие эффекта, если закрыто
   
    function handleClickOutside(event: MouseEvent) {
      const { target } = event;
      
      const isOutsideClick =
        target instanceof Node && // проверяем, что это `DOM`-элемент
        rootRef.current &&
        !rootRef.current.contains(target); // проверяем, что кликнули на элемент, который находится не внутри блока
      if (isOutsideClick) {
        onClose();
      }
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    document.addEventListener("keydown", handleEscape);
    document.addEventListener("mousedown", handleClickOutside);

    //  Обязательно удаляем обработчики в `clean-up`- функции
    return () => {
      document.removeEventListener("keydown", handleEscape);
      document.removeEventListener("mousedown", handleClickOutside);
    };
    
    // Обязательно следим за `isOpen`, чтобы срабатывало только при открытии, 
    // а не при любой перерисовке компонента
  }, [isOpen, onClose, rootRef]);
}
```
Этот код помещают в отдельный файл `useClose.ts` в папке `hooks` на одном уровне с папкой `components` и импортируют хук туда, где нужно.
Теперь его можно использовать в любом компоненте (попапе, меню и тд), которому нужно установить эти обработчики.

Пример того, как это использовать:
```
    // Создаем `ref` для формы и указываем его на внешнем блоке с формой
    const formRef = useRef<HTMLElement | null>(null);
    
    useClose({
        isOpen,
        onClose: () => setIsOpen(false),
        rootRef: formRef,
    });

2024-05-02 12:26 UTC, korvintaG commented
Спасибо за внимание, проявленное к моей работе!

2024-05-03 09:56 UTC, olgalatkina approved these changes
Добрый день.

**Отличная работа! Проект принимается**🎉

Успехов в дальнейшем обучении!

2024-05-03 09:56 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleSubmit = (e: SyntheticEvent): void => {
**Можно лучше:**
Прости, пропустила в прошлом ревью пару замечаний🙏
Здесь лучше сузить типизацию события до `FormEvent<HTMLFormElement>`

2024-05-03 09:56 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<Select
**Можно лучше:**
Для компонентов без содержимого используем самозакрывающиеся теги:
```
<Select
    title='Шрифты'
    options={fontFamilyOptions}
    selected={fontFamilyOption}
    onChange={setFontFamilyOption}
/>
```

2024-05-03 12:13 UTC, merged